### ISSUE TITLE
problems with the example  "muc"

### ISSUE THREAD

**Issue by ander2000** [ESTOS/strophe.jingle#62]
Hi how's everything? I'm having several issues starting the example code, it shows me the following:
muc.js:362 Uncaught ReferenceError: setupRTC is not defined
    at HTMLDocument.<anonymous> (muc.js:362:5)
    at l (jquery.min.js:2:16996)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:17783)
    at Function.ready (jquery.min.js:2:12504)
    at HTMLDocument.A (jquery.min.js:2:9909)

**Comment by fippo** [comment]
you'll need to copy the files that are missing from the toplevel directory.

FWIW: i'd be surprised if this still works after almost a decade...
